### ISSUE TITLE
Add a configurable limit to the number of pages you can lock at one time

### ISSUE THREAD

**Issue by Wolfkhan66** [thecogworks/Cogworks.ContentGuard#15] opened 2021-04-20 10:36 UTC
After deploying to production i checked the relations table and noticed some users locking 20+ nodes at one time. 
Is it possible to add a locking limit and treat the relations like a filo queue so only the most recent #{e.g 3} nodes are locked.

**Comment by Wolfkhan66** [comment] 2021-04-20 14:41
Realized this would probably be resolved by the other feature requests to auto remove relations on leaving a page.

**Comment by mzajkowski** [comment] 2021-04-22 13:52
Hey @Wolfkhan66! Great topic and yes, the idea was to clean up these relations "somehow". The problem is with determining e.g. if an editor is not editing the same page in multiple tabs for example. As then it won't be that obvious that the page was left and the editorial process was finished.

We thought about session info stored somewhere, but the initial release supposed to be really simple. I need to investigate how it can be done and we'd love to see some ideas and maybe PRs with the approaches which maybe we didn't catch yet.

That's definitely an issue here though which we need to tackle at some point!

**Comment by mzajkowski** [comment] 2021-04-22 13:53
I'll close this issue as I think that limit won't solve the issue and will just make it possible to lose the main functionality. Let's discuss the other approaches on open issues. Ideas more than welcome!

**Closed as completed by mzajkowski** 2021-04-22 13:53 UTC
